version: "2"
services:
    mysql:
        image:                      mysql:8.2
        container_name:             mi-mysql
        ports:
                                  - 3306:3306
        volumes:
                                  - /home/ubuntu/environment/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:    password
            MYSQL_DATABASE:         animalitos
            MYSQL_USER:             usuario
            MYSQL_PASSWORD:         password
    node-dev:
        image:                      node:18.18
        container_name:             mi-mysql
        ports:
                                  - 3306:3306
        volumes:
                                  - /home/ubuntu/environment/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:    password
            MYSQL_DATABASE:         animalitos
            MYSQL_USER:             usuario
            MYSQL_PASSWORD:         password            
    node-prod:
        image: 
        build:                      .