version: "2"
services:
    basededatos:
        image:                      mysql:8.2
        container_name:             mi-mysql
        ports:
                                  - 3306:3306
        volumes:
                                  - /home/ubuntu/environment/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:    password
            MYSQL_DATABASE:         animalitos
            MYSQL_USER:             usuario
            MYSQL_PASSWORD:         password

    desarrollo:
        image:                      node:18.18
        container_name:             desarrollo
        volumes:
                                  - $PWD/..:/app
        working_dir:                /app
        environment: 
            DB_NAME:                animalitos
            DB_USER:                usuario
            DB_PASS:                password
            DB_HOST:                basededatos
        command:
            - sleep
            - "3600"